extends: ["spectral:oas"]

rules:
  # Custom rules for LiveTable API
  operation-description: true
  operation-operationId: true
  operation-tags: false # Allow operations without tags for simplicity

  # Security requirements
  openapi-tags: false
  info-contact: true
  info-description: true
  info-license: true
